# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$CANDY_SECURE" == "candy" ]
          then
            echo "Got secret"
          fi
          if [ "$PEAR_SECURE" == "pear" ]
          then
            echo "Got secret something else"
          fi
        env:
          PROBANDO: ${{ secrets.PROBANDO }}
